ready for expertise version of an app
sysy-inc/pzsp2-24z pull request #13
Opened 2024-11-25 09:29 UTC by jasiollo

2024-11-25 21:11 UTC, xDepcio approved these changes

2024-12-04 16:23 UTC, jedrzej-grabski requested changes

2024-12-04 16:23 UTC, jedrzej-grabski commented on ui_ux/historical_data_page.png
ten kalendarz to nie jest troche krzywo XD?

2024-12-05 22:46 UTC, jasiollo commented on ui_ux/historical_data_page.png
Może dlatego, że tutaj taki 3D to złudzenie jest, że krzywo, sprawdzę w figmie

2024-12-09 01:04 UTC, merged